insert into  public."Veiculo" values( 1 , 'Peugeot ', '2008 ');
insert into  public."Veiculo" values( 2 , 'Peugeot ', '207 ');
insert into  public."Veiculo" values( 3 , 'Peugeot ', '207 Sedan ');
insert into  public."Veiculo" values( 4 , 'Peugeot ', '207 SW ');
insert into  public."Veiculo" values( 5 , 'Peugeot ', '208 ');
insert into  public."Veiculo" values( 6 , ' ', '2500 ');
insert into  public."Veiculo" values( 7 , 'Peugeot ', '3008 ');
insert into  public."Veiculo" values( 8 , 'Peugeot ', '307 ');
insert into  public."Veiculo" values( 9 , 'Peugeot ', '308 ');
insert into  public."Veiculo" values( 10 , 'Peugeot ', '308 CC ');
insert into  public."Veiculo" values( 11 , ' ', '320 ');
insert into  public."Veiculo" values( 12 , 'Peugeot ', '408 ');
insert into  public."Veiculo" values( 13 , ' ', '458 ');
insert into  public."Veiculo" values( 14 , ' ', '500 ');
insert into  public."Veiculo" values( 15 , ' ', '500 Abarth ');
insert into  public."Veiculo" values( 16 , 'Peugeot ', '5008 ');
insert into  public."Veiculo" values( 17 , 'Peugeot ', '508 ');
insert into  public."Veiculo" values( 18 , 'BMW ', '530 ');
insert into  public."Veiculo" values( 19 , ' ', '620 ');
insert into  public."Veiculo" values( 20 , ' ', '911 ');
insert into  public."Veiculo" values( 21 , 'Audi ', 'A1 ');
insert into  public."Veiculo" values( 22 , 'Audi ', 'A3 ');
insert into  public."Veiculo" values( 23 , 'Audi ', 'A3 Sedan ');
insert into  public."Veiculo" values( 24 , 'Audi ', 'A4 ');
insert into  public."Veiculo" values( 25 , 'Audi ', 'A4 Avant ');
insert into  public."Veiculo" values( 26 , 'Audi ', 'A5 ');
insert into  public."Veiculo" values( 27 , 'Audi ', 'A6 ');
insert into  public."Veiculo" values( 28 , 'Audi ', 'A7 ');
insert into  public."Veiculo" values( 29 , 'Audi ', 'A8 ');
insert into  public."Veiculo" values( 30 , 'Honda ', 'Accord ');
insert into  public."Veiculo" values( 31 , ' ', 'Actyon ');
insert into  public."Veiculo" values( 32 , ' ', 'Actyon Sports ');
insert into  public."Veiculo" values( 33 , 'Chevrolet ', 'Agile ');
insert into  public."Veiculo" values( 34 , 'Citroen ', 'Aircross ');
insert into  public."Veiculo" values( 35 , ' ', 'Alaskan ');
insert into  public."Veiculo" values( 36 , 'Nissan ', 'Altima ');
insert into  public."Veiculo" values( 37 , 'Volkswagen ', 'Amarok ');
insert into  public."Veiculo" values( 38 , ' ', 'AMG GT ');
insert into  public."Veiculo" values( 39 , 'Fiat ', 'Argo ');
insert into  public."Veiculo" values( 40 , 'Chevrolet ', 'Astra Hatch ');
insert into  public."Veiculo" values( 41 , 'Chevrolet ', 'Astra Sedan ');
insert into  public."Veiculo" values( 42 , 'Mitsubishi ', 'ASX ');
insert into  public."Veiculo" values( 43 , 'Hyundai ', 'Azera ');
insert into  public."Veiculo" values( 44 , 'Chevrolet ', 'Blazer ');
insert into  public."Veiculo" values( 45 , ' ', 'Bolt ');
insert into  public."Veiculo" values( 46 , ' ', 'Bongo ');
insert into  public."Veiculo" values( 47 , ' ', 'Boxer ');
insert into  public."Veiculo" values( 48 , ' ', 'Boxster ');
insert into  public."Veiculo" values( 49 , ' ', 'Boxster S ');
insert into  public."Veiculo" values( 50 , ' ', 'Bravo ');
insert into  public."Veiculo" values( 51 , 'Citroen ', 'C3 ');
insert into  public."Veiculo" values( 52 , 'Citroen ', 'C3 Picasso ');
insert into  public."Veiculo" values( 53 , 'Citroen ', 'C30 ');
insert into  public."Veiculo" values( 54 , 'Citroen ', 'C4 ');
insert into  public."Veiculo" values( 55 , 'Citroen ', 'C4 Cactus ');
insert into  public."Veiculo" values( 56 , 'Citroen ', 'C4 Lounge ');
insert into  public."Veiculo" values( 57 , 'Citroen ', 'C4 Pallas ');
insert into  public."Veiculo" values( 58 , 'Citroen ', 'C4 Picasso ');
insert into  public."Veiculo" values( 59 , 'Citroen ', 'C5 ');
insert into  public."Veiculo" values( 60 , 'Citroen ', 'C5 Tourer ');
insert into  public."Veiculo" values( 61 , 'Kia ', 'Cadenza ');
insert into  public."Veiculo" values( 62 , ' ', 'California ');
insert into  public."Veiculo" values( 63 , 'Chevrolet ', 'Camaro ');
insert into  public."Veiculo" values( 64 , 'Toyota ', 'Camry ');
insert into  public."Veiculo" values( 65 , 'Cherry ', 'Caoa Chery Arrizo 5 ');
insert into  public."Veiculo" values( 66 , 'Chevrolet ', 'Captiva ');
insert into  public."Veiculo" values( 67 , 'Renault ', 'Captur ');
insert into  public."Veiculo" values( 68 , 'Kia ', 'Carens ');
insert into  public."Veiculo" values( 69 , 'Kia ', 'Carnival ');
insert into  public."Veiculo" values( 70 , 'Porsche ', 'Cayenne ');
insert into  public."Veiculo" values( 71 , 'Porsche ', 'Cayman ');
insert into  public."Veiculo" values( 72 , 'Porsche ', 'Cayman S ');
insert into  public."Veiculo" values( 73 , ' ', 'Celer Hatch ');
insert into  public."Veiculo" values( 74 , ' ', 'Celer Sedan ');
insert into  public."Veiculo" values( 75 , 'Chevrolet ', 'Celta ');
insert into  public."Veiculo" values( 76 , 'Kia ', 'Cerato ');
insert into  public."Veiculo" values( 77 , ' ', 'Chana Cargo ');
insert into  public."Veiculo" values( 78 , ' ', 'Chana Family ');
insert into  public."Veiculo" values( 79 , ' ', 'Chana Utility ');
insert into  public."Veiculo" values( 80 , 'Jeep ', 'Cherokee ');
insert into  public."Veiculo" values( 81 , 'Chevrolet ', 'Cielo Hatch ');
insert into  public."Veiculo" values( 82 , 'Chevrolet ', 'Cielo Sedan ');
insert into  public."Veiculo" values( 83 , 'Honda ', 'City ');
insert into  public."Veiculo" values( 84 , 'Honda ', 'Civic ');
insert into  public."Veiculo" values( 85 , 'Honda ', 'Civic Si ');
insert into  public."Veiculo" values( 86 , 'Mercedes ', 'CLA ');
insert into  public."Veiculo" values( 87 , 'Mercedes ', 'Classe A ');
insert into  public."Veiculo" values( 88 , 'Mercedes ', 'Classe A Sedan ');
insert into  public."Veiculo" values( 89 , 'Mercedes ', 'Classe B ');
insert into  public."Veiculo" values( 90 , 'Mercedes ', 'Classe C ');
insert into  public."Veiculo" values( 91 , 'Mercedes ', 'Classe C 250 Turbo Sport ');
insert into  public."Veiculo" values( 92 , 'Mercedes ', 'Classe C 63 AMG Touring ');
insert into  public."Veiculo" values( 93 , 'Mercedes ', 'Classe CL ');
insert into  public."Veiculo" values( 94 , 'Mercedes ', 'Classe CLS 63 AMG ');
insert into  public."Veiculo" values( 95 , 'Mercedes ', 'Classe E ');
insert into  public."Veiculo" values( 96 , 'Mercedes ', 'Classe G ');
insert into  public."Veiculo" values( 97 , 'Mercedes ', 'Classe GLK ');
insert into  public."Veiculo" values( 98 , 'Mercedes ', 'Classe S ');
insert into  public."Veiculo" values( 99 , 'Mercedes ', 'Classe S 400 Hybrid ');
insert into  public."Veiculo" values( 100 , 'Mercedes ', 'Classe SLK ');
insert into  public."Veiculo" values( 101 , 'Mercedes ', 'Classe SLS AMG ');
insert into  public."Veiculo" values( 102 , 'Mercedes ', 'Classe X ');
insert into  public."Veiculo" values( 103 , 'Chevrolet ', 'Classic ');
insert into  public."Veiculo" values( 104 , 'Renault ', 'Clio ');
insert into  public."Veiculo" values( 105 , 'Chevrolet ', 'Cobalt ');
insert into  public."Veiculo" values( 106 , 'Jeep ', 'Compass ');
insert into  public."Veiculo" values( 107 , ' ', 'Continental Flying Spur ');
insert into  public."Veiculo" values( 108 , ' ', 'Continental Supersports Coupé ');
insert into  public."Veiculo" values( 109 , ' ', 'Cooper ');
insert into  public."Veiculo" values( 110 , ' ', 'Cooper Cabrio ');
insert into  public."Veiculo" values( 111 , ' ', 'Cooper Countryman ');
insert into  public."Veiculo" values( 112 , ' ', 'Cooper S Clubman-Hampton ');
insert into  public."Veiculo" values( 113 , 'Toyota ', 'Corolla ');
insert into  public."Veiculo" values( 114 , 'Chevrolet ', 'Corsa Hatch ');
insert into  public."Veiculo" values( 115 , 'Chevrolet ', 'Corsa Sedã ');
insert into  public."Veiculo" values( 116 , 'Ford ', 'Courier ');
insert into  public."Veiculo" values( 117 , 'Hon ', 'CR-V ');
insert into  public."Veiculo" values( 118 , 'Hyundai ', 'Creta ');
insert into  public."Veiculo" values( 119 , 'Fiat ', 'Cronos ');
insert into  public."Veiculo" values( 120 , 'Volkswagem ', 'Crossfox ');
insert into  public."Veiculo" values( 121 , 'Chevrolet ', 'Cruze ');
insert into  public."Veiculo" values( 122 , 'Chevrolet ', 'Cruze Sport6 ');
insert into  public."Veiculo" values( 123 , ' ', 'CT200h ');
insert into  public."Veiculo" values( 124 , ' ', 'Daily 35S14 ');
insert into  public."Veiculo" values( 125 , ' ', 'DB9 Volante ');
insert into  public."Veiculo" values( 126 , ' ', 'DBS Coupe ');
insert into  public."Veiculo" values( 127 , ' ', 'DBS Volante ');
insert into  public."Veiculo" values( 128 , ' ', 'Defender ');
insert into  public."Veiculo" values( 129 , 'Land Rover ', 'Discovery ');
insert into  public."Veiculo" values( 130 , 'Land Rover ', 'Discovery Sport ');
insert into  public."Veiculo" values( 131 , 'Fiat ', 'Doblò ');
insert into  public."Veiculo" values( 132 , 'Fiat ', 'Doblò Cargo ');
insert into  public."Veiculo" values( 133 , 'Citroen ', 'DS3 ');
insert into  public."Veiculo" values( 134 , 'Citroen ', 'DS5 ');
insert into  public."Veiculo" values( 135 , ' ', 'Ducato ');
insert into  public."Veiculo" values( 136 , ' ', 'Durango ');
insert into  public."Veiculo" values( 137 , 'Renault ', 'Duster ');
insert into  public."Veiculo" values( 138 , ' ', 'E-Tron ');
insert into  public."Veiculo" values( 139 , ' ', 'EC7 ');
insert into  public."Veiculo" values( 140 , 'Mitsubishi ', 'Eclipse Cross ');
insert into  public."Veiculo" values( 141 , 'Ford ', 'EcoSport ');
insert into  public."Veiculo" values( 142 , 'Ford ', 'Edge ');
insert into  public."Veiculo" values( 143 , ' ', 'Effa Hafei Furgão ');
insert into  public."Veiculo" values( 144 , ' ', 'Effa Hafei Picape Baú ');
insert into  public."Veiculo" values( 145 , ' ', 'Effa Hafei Picape Cabine Dupla ');
insert into  public."Veiculo" values( 146 , ' ', 'Effa Hafei Picape Cabine Simples ');
insert into  public."Veiculo" values( 147 , ' ', 'Effa Hafei Van ');
insert into  public."Veiculo" values( 148 , ' ', 'Effa M100 ');
insert into  public."Veiculo" values( 149 , 'Hyundai ', 'Elantra ');
insert into  public."Veiculo" values( 150 , 'Chevrolet ', 'Equinox ');
insert into  public."Veiculo" values( 151 , ' ', 'Equus ');
insert into  public."Veiculo" values( 152 , 'Toyota ', 'Etios ');
insert into  public."Veiculo" values( 153 , 'Toyota ', 'Etios Sedã ');
insert into  public."Veiculo" values( 154 , 'Ford ', 'F-250 ');
insert into  public."Veiculo" values( 155 , 'Ford ', 'F-Pace ');
insert into  public."Veiculo" values( 156 , ' ', 'F-Type Coupé ');
insert into  public."Veiculo" values( 157 , ' ', 'F599 GTO ');
insert into  public."Veiculo" values( 158 , ' ', 'Face ');
insert into  public."Veiculo" values( 159 , ' ', 'Fastback ');
insert into  public."Veiculo" values( 160 , 'Fiat ', 'Fiat Mobi ');
insert into  public."Veiculo" values( 161 , 'Fiat ', 'Fiat Toro ');
insert into  public."Veiculo" values( 162 , 'Ford ', 'Fiesta ');
insert into  public."Veiculo" values( 163 , 'Ford ', 'Fiesta Rocam Hatch ');
insert into  public."Veiculo" values( 164 , 'Ford ', 'Fiesta Rocam Sedan ');
insert into  public."Veiculo" values( 165 , 'Fiat ', 'Fiorino ');
insert into  public."Veiculo" values( 166 , 'Honda ', 'Fit ');
insert into  public."Veiculo" values( 167 , 'Renault ', 'Fluence ');
insert into  public."Veiculo" values( 168 , 'Ford ', 'Focus ');
insert into  public."Veiculo" values( 169 , 'Ford ', 'Focus Fastback ');
insert into  public."Veiculo" values( 170 , ' ', 'Forester ');
insert into  public."Veiculo" values( 171 , ' ', 'Fortwo MHD ');
insert into  public."Veiculo" values( 172 , ' ', 'Fortwo Passion Cabrio ');
insert into  public."Veiculo" values( 173 , ' ', 'Fortwo Passion Coupé ');
insert into  public."Veiculo" values( 174 , 'Volkswagen ', 'Fox ');
insert into  public."Veiculo" values( 175 , 'Land Rover ', 'Freelander 2 ');
insert into  public."Veiculo" values( 176 , 'Dodge ', 'Freemont ');
insert into  public."Veiculo" values( 177 , 'Nissan ', 'Frontier ');
insert into  public."Veiculo" values( 178 , 'Volkswagen ', 'Fusca ');
insert into  public."Veiculo" values( 179 , 'Ford ', 'Fusion ');
insert into  public."Veiculo" values( 180 , ' ', 'Gallardo LP 560 - 4 ');
insert into  public."Veiculo" values( 181 , ' ', 'Gallardo LP 560 - 4 Spyder ');
insert into  public."Veiculo" values( 182 , ' ', 'GC2 ');
insert into  public."Veiculo" values( 183 , ' ', 'Ghibli ');
insert into  public."Veiculo" values( 184 , ' ', 'GLA ');
insert into  public."Veiculo" values( 185 , ' ', 'GLC ');
insert into  public."Veiculo" values( 186 , ' ', 'GLE ');
insert into  public."Veiculo" values( 187 , ' ', 'GLE Coupé ');
insert into  public."Veiculo" values( 188 , ' ', 'GLS ');
insert into  public."Veiculo" values( 189 , 'Volkswagen ', 'Gol ');
insert into  public."Veiculo" values( 190 , 'Volkswagen ', 'Gol G4 ');
insert into  public."Veiculo" values( 191 , 'Volkswagen ', 'Golf '); 
insert into  public."Veiculo" values( 192 , 'Volkswagen ', 'Golf Variant ');
insert into  public."Veiculo" values( 193 , ' ', 'Gran Cabrio ');
insert into  public."Veiculo" values( 194 , ' ', 'Gran Turismo ');
insert into  public."Veiculo" values( 195 , 'Jeep ', 'Grand Cherokee ');
insert into  public."Veiculo" values( 196 , 'Nissan ', 'Grand Livina ');
insert into  public."Veiculo" values( 197 , 'Fiat ', 'Grand Siena ');
insert into  public."Veiculo" values( 198 , ' ', 'Grand Tour ');
insert into  public."Veiculo" values( 199 , ' ', 'GT-R ');
insert into  public."Veiculo" values( 200 , 'Hyudai ', 'HB20 ');
insert into  public."Veiculo" values( 201 , 'Hyudai ', 'HB20S ');
insert into  public."Veiculo" values( 202 , 'Hyudai ', 'HB20X ');
insert into  public."Veiculo" values( 203 , 'Toyota ', 'Hilux ');
insert into  public."Veiculo" values( 204 , 'Peugeot ', 'Hoggar ');
insert into  public."Veiculo" values( 205 , ' ', 'HR ');
insert into  public."Veiculo" values( 206 , 'Honda ', 'HR-V ');
insert into  public."Veiculo" values( 207 , ' ', 'i3 ');
insert into  public."Veiculo" values( 208 , 'Hyundai ', 'i30 ');
insert into  public."Veiculo" values( 209 , 'Hyundai ', 'i30 CW ');
insert into  public."Veiculo" values( 210 , 'Fiat ', 'Idea ');
insert into  public."Veiculo" values( 211 , ' ', 'Impreza Hatch ');
insert into  public."Veiculo" values( 212 , ' ', 'Impreza Sedã ');
insert into  public."Veiculo" values( 213 , 'Hyundai ', 'iX35 ');
insert into  public."Veiculo" values( 214 , ' ', 'J2 ');
insert into  public."Veiculo" values( 215 , ' ', 'J3 ');
insert into  public."Veiculo" values( 216 , ' ', 'J3 Turin ');
insert into  public."Veiculo" values( 217 , ' ', 'J5 ');
insert into  public."Veiculo" values( 218 , ' ', 'J6 ');
insert into  public."Veiculo" values( 219 , ' ', 'Jac T50 ');
insert into  public."Veiculo" values( 220 , ' ', 'Jaguar I-Pace ');
insert into  public."Veiculo" values( 221 , ' ', 'Jeep Renegade ');
insert into  public."Veiculo" values( 222 , 'Volkswagen ', 'Jetta ');
insert into  public."Veiculo" values( 223 , 'Volkswagen ', 'Jetta Variant ');
insert into  public."Veiculo" values( 224 , ' ', 'Jimny ');
insert into  public."Veiculo" values( 225 , ' ', 'Journey ');
insert into  public."Veiculo" values( 226 , ' ', 'Joy ');
insert into  public."Veiculo" values( 227 , ' ', 'Jumper ');
insert into  public."Veiculo" values( 228 , 'Ford ', 'Ka ');
insert into  public."Veiculo" values( 229 , 'Ford ', 'Ka+ ');
insert into  public."Veiculo" values( 230 , ' ', 'Kangoo Express ');
insert into  public."Veiculo" values( 231 , 'Nissan ', 'Kicks ');
insert into  public."Veiculo" values( 232 , ' ', 'Kombi ');
insert into  public."Veiculo" values( 233 , ' ', 'Korando ');
insert into  public."Veiculo" values( 234 , 'Renault ', 'Kwid ');
insert into  public."Veiculo" values( 235 , ' ', 'Kyron ');
insert into  public."Veiculo" values( 236 , 'Mitsubishi ', 'L200 Outdoor ');
insert into  public."Veiculo" values( 237 , 'Mitsubishi ', 'L200 Savana ');
insert into  public."Veiculo" values( 238 , 'Mitsubishi ', 'L200 Triton ');
insert into  public."Veiculo" values( 239 , 'Mitsubishi ', 'Lancer ');
insert into  public."Veiculo" values( 240 , 'Mitsubishi ', 'Lancer Evolution X ');
insert into  public."Veiculo" values( 241 , ' ', 'Leaf ');
insert into  public."Veiculo" values( 242 , ' ', 'Legacy ');
insert into  public."Veiculo" values( 243 , 'Fiat ', 'Linea ');
insert into  public."Veiculo" values( 244 , 'Nissan ', 'Livina ');
insert into  public."Veiculo" values( 245 , 'Renault ', 'Logan ');
insert into  public."Veiculo" values( 246 , ' ', 'M2 Coupé ');
insert into  public."Veiculo" values( 247 , ' ', 'Macan ');
insert into  public."Veiculo" values( 248 , ' ', 'Mahindra Picape ');
insert into  public."Veiculo" values( 249 , ' ', 'Mahindra SUV ');
insert into  public."Veiculo" values( 250 , ' ', 'Malibu ');
insert into  public."Veiculo" values( 251 , 'Nisssan ', 'March ');
insert into  public."Veiculo" values( 252 , ' ', 'Marruá ');
insert into  public."Veiculo" values( 253 , ' ', 'Master ');
insert into  public."Veiculo" values( 254 , 'Fiat ', 'Meriva ');
insert into  public."Veiculo" values( 255 , ' ', 'MG 550 ');
insert into  public."Veiculo" values( 256 , ' ', 'MG 6 ');
insert into  public."Veiculo" values( 257 , 'Fiat ', 'Mille ');
insert into  public."Veiculo" values( 258 , ' ', 'Mini Clubman ');
insert into  public."Veiculo" values( 259 , ' ', 'Mohave ');
insert into  public."Veiculo" values( 260 , 'Chevrolet ', 'Montana ');
insert into  public."Veiculo" values( 261 , 'Ford ', 'Mustang ');
insert into  public."Veiculo" values( 262 , 'Ford ', 'New Fiesta ');
insert into  public."Veiculo" values( 263 , 'Hyundai ', 'New Tucson ');
insert into  public."Veiculo" values( 264 , 'Volkswagen ', 'Nivus ');
insert into  public."Veiculo" values( 265 , ' ', 'NX 200t ');
insert into  public."Veiculo" values( 266 , 'Chevrolet ', 'Omega ');
insert into  public."Veiculo" values( 267 , ' ', 'One ');
insert into  public."Veiculo" values( 268 , 'Cheverolet ', 'Onix ');
insert into  public."Veiculo" values( 269 , 'Cheverolet ', 'Onix Plus ');
insert into  public."Veiculo" values( 270 , 'Kia ', 'Optima ');
insert into  public."Veiculo" values( 271 , 'Renault ', 'Oroch ');
insert into  public."Veiculo" values( 272 , ' ', 'Outback ');
insert into  public."Veiculo" values( 273 , 'Mitsubishi ', 'Outlander ');
insert into  public."Veiculo" values( 274 , 'Mitsubishi ', 'Pajero Dakar ');
insert into  public."Veiculo" values( 275 , 'Mitsubishi ', 'Pajero Full ');
insert into  public."Veiculo" values( 276 , 'Mitsubishi ', 'Pajero Sport ');
insert into  public."Veiculo" values( 277 , 'Mitsubishi ', 'Pajero TR4 ');
insert into  public."Veiculo" values( 278 , 'Fiat ', 'Palio ');
insert into  public."Veiculo" values( 279 , 'Fiat ', 'Palio Adventure ');
insert into  public."Veiculo" values( 280 , 'Porsche ', 'Panamera ');
insert into  public."Veiculo" values( 281 , 'Volkswagen ', 'Parati ');
insert into  public."Veiculo" values( 282 , ' ', 'Partner ');
insert into  public."Veiculo" values( 283 , 'Volkswagen ', 'Passat ');
insert into  public."Veiculo" values( 284 , 'Volkswagen ', 'Passat Variant ');
insert into  public."Veiculo" values( 285 , 'Kia ', 'Picanto ');
insert into  public."Veiculo" values( 286 , ' ', 'Pick-up ');
insert into  public."Veiculo" values( 287 , 'Volkswagen ', 'Polo ');
insert into  public."Veiculo" values( 288 , 'Volkswagen ', 'Polo Sedan ');
insert into  public."Veiculo" values( 289 , ' ', 'Portofino ');
insert into  public."Veiculo" values( 290 , 'Chevrolet ', 'Prisma ');
insert into  public."Veiculo" values( 291 , 'Toyota ', 'Prius ');
insert into  public."Veiculo" values( 292 , 'Fiat ', 'Punto ');
insert into  public."Veiculo" values( 293 , 'Audi ', 'Q3 ');
insert into  public."Veiculo" values( 294 , 'Audi ', 'Q5 ');
insert into  public."Veiculo" values( 295 , 'Audi ', 'Q7 ');
insert into  public."Veiculo" values( 296 , 'Audi ', 'QQ ');
insert into  public."Veiculo" values( 297 , ' ', 'Quattroporte ');
insert into  public."Veiculo" values( 298 , 'Audi ', 'R8 ');
insert into  public."Veiculo" values( 299 , 'Audi ', 'R8 GT ');
insert into  public."Veiculo" values( 300 , 'Land Rover ', 'Range Rover Evoque ');
insert into  public."Veiculo" values( 301 , 'Land Rover ', 'Range Rover Sport ');
insert into  public."Veiculo" values( 302 , 'Land Rover ', 'Range Rover Vogue ');
insert into  public."Veiculo" values( 303 , 'Ford ', 'Ranger ');
insert into  public."Veiculo" values( 304 , ' ', 'Rapide ');
insert into  public."Veiculo" values( 305 , 'Toyota ', 'RAV4 ');
insert into  public."Veiculo" values( 306 , ' ', 'RCZ ');
insert into  public."Veiculo" values( 307 , ' ', 'Rexton ');
insert into  public."Veiculo" values( 308 , ' ', 'RS 3 Sportback ');
insert into  public."Veiculo" values( 309 , ' ', 'RS 5 ');
insert into  public."Veiculo" values( 310 , ' ', 'RS6 Avant ');
insert into  public."Veiculo" values( 311 , ' ', 'S-18 ');
insert into  public."Veiculo" values( 312 , ' ', 'S-Cross ');
insert into  public."Veiculo" values( 313 , 'Chevrolet ', 'S10 ');
insert into  public."Veiculo" values( 314 , ' ', 'S60 ');
insert into  public."Veiculo" values( 315 , 'Renault ', 'Sandero ');
insert into  public."Veiculo" values( 316 , 'Renault ', 'Sandero RS ');
insert into  public."Veiculo" values( 317 , 'Renault ', 'Sandero Stepway ');
insert into  public."Veiculo" values( 318 , 'Hyundai ', 'Santa Fe ');
insert into  public."Veiculo" values( 319 , 'Volkswagen ', 'Saveiro ');
insert into  public."Veiculo" values( 320 , 'Nissan ', 'Sentra ');
insert into  public."Veiculo" values( 321 , 'BMW ', 'Série 1 ');
insert into  public."Veiculo" values( 322 , 'BMW ', 'Série 1 Cabrio ');
insert into  public."Veiculo" values( 323 , 'BMW ', 'Série 1 Coupé ');
insert into  public."Veiculo" values( 324 , 'BMW ', 'Série 1 M ');
insert into  public."Veiculo" values( 325 , 'BMW ', 'Série 3 Cabrio ');
insert into  public."Veiculo" values( 326 , 'BMW ', 'Série 3 M3 Coupé ');
insert into  public."Veiculo" values( 327 , 'BMW ', 'Série 3 M3 Sedã ');
insert into  public."Veiculo" values( 328 , 'BMW ', 'Série 3 Sedã ');
insert into  public."Veiculo" values( 329 , 'BMW ', 'Série 5 Gran Turismo ');
insert into  public."Veiculo" values( 330 , 'BMW ', 'Série 5 Sedã ');
insert into  public."Veiculo" values( 331 , 'BMW ', 'Série 7 Sedã ');
insert into  public."Veiculo" values( 332 , ' ', 'Siena EL ');
insert into  public."Veiculo" values( 333 , 'Hyundai ', 'Sonata ');
insert into  public."Veiculo" values( 334 , 'Chevrolet ', 'Sonic ');
insert into  public."Veiculo" values( 335 , 'Kia ', 'Sorento ');
insert into  public."Veiculo" values( 336 , 'Kia ', 'Soul ');
insert into  public."Veiculo" values( 337 , 'Volkswagen ', 'Space Cross ');
insert into  public."Veiculo" values( 338 , 'Volkswagen ', 'SpaceFox ');
insert into  public."Veiculo" values( 339 , 'Chevrolet ', 'Spin ');
insert into  public."Veiculo" values( 340 , 'Kia ', 'Sportage ');
insert into  public."Veiculo" values( 341 , 'Fiat ', 'Strada ');
insert into  public."Veiculo" values( 342 , 'Toyota ', 'SW4 ');
insert into  public."Veiculo" values( 343 , ' ', 'SX4 ');
insert into  public."Veiculo" values( 344 , ' ', 'Symbol ');
insert into  public."Veiculo" values( 345 , 'Volkswagen ', 'T-Cross ');
insert into  public."Veiculo" values( 346 , ' ', 'T4 ');
insert into  public."Veiculo" values( 347 , ' ', 'T40 ');
insert into  public."Veiculo" values( 348 , ' ', 'T5 ');
insert into  public."Veiculo" values( 349 , ' ', 'T6 ');
insert into  public."Veiculo" values( 350 , ' ', 'T80 ');
insert into  public."Veiculo" values( 351 , ' ', 'Taycan ');
insert into  public."Veiculo" values( 352 , 'Cherry ', 'Tiggo 2 ');
insert into  public."Veiculo" values( 353 , 'Cherry ', 'Tiggo 5X ');
insert into  public."Veiculo" values( 354 , 'Volkswagen ', 'Tiguan ');
insert into  public."Veiculo" values( 355 , 'Nissan ', 'Tiida Hatch ');
insert into  public."Veiculo" values( 356 , 'Nissan ', 'Tiida Sedan ');
insert into  public."Veiculo" values( 357 , ' ', 'Tivoli ');
insert into  public."Veiculo" values( 358 , ' ', 'Topic Furgão ');
insert into  public."Veiculo" values( 359 , ' ', 'Topic Passageiro ');
insert into  public."Veiculo" values( 360 , ' ', 'Touareg ');
insert into  public."Veiculo" values( 361 , ' ', 'Town & Country ');
insert into  public."Veiculo" values( 362 , ' ', 'Towner Furgão ');
insert into  public."Veiculo" values( 363 , ' ', 'Towner Jr ');
insert into  public."Veiculo" values( 364 , ' ', 'Towner Passageiro ');
insert into  public."Veiculo" values( 365 , 'Cheverolet ', 'Tracker ');
insert into  public."Veiculo" values( 366 , ' ', 'Trailblazer ');
insert into  public."Veiculo" values( 367 , ' ', 'Transit ');
insert into  public."Veiculo" values( 368 , ' ', 'Tribeca ');
insert into  public."Veiculo" values( 369 , 'Audi ', 'TT ');
insert into  public."Veiculo" values( 370 , 'Audi ', 'TT Roadster ');
insert into  public."Veiculo" values( 371 , 'Hyundai ', 'Tucson ');
insert into  public."Veiculo" values( 372 , 'Fiat ', 'Uno ');
insert into  public."Veiculo" values( 373 , 'Volkswagen ', 'Up! ');
insert into  public."Veiculo" values( 374 , ' ', 'V12 Vantage Coupe ');
insert into  public."Veiculo" values( 375 , ' ', 'V40 ');
insert into  public."Veiculo" values( 376 , ' ', 'V8 Vantage Coupe ');
insert into  public."Veiculo" values( 377 , ' ', 'V8 Vantage Roadster ');
insert into  public."Veiculo" values( 378 , 'Chevrolet ', 'Vectra ');
insert into  public."Veiculo" values( 379 , 'Chevrolet ', 'Vectra GT ');
insert into  public."Veiculo" values( 380 , ' ', 'Velar ');
insert into  public."Veiculo" values( 381 , 'Hyundai ', 'Veloster ');
insert into  public."Veiculo" values( 382 , 'Hyundai ', 'Veracruz ');
insert into  public."Veiculo" values( 383 , 'Nissan ', 'Versa ');
insert into  public."Veiculo" values( 384 , ' ', 'Virage ');
insert into  public."Veiculo" values( 385 , 'Volskwagen ', 'Virtus ');
insert into  public."Veiculo" values( 386 , 'Nissan ', 'Vitara ');
insert into  public."Veiculo" values( 387 , ' ', 'Vito ');
insert into  public."Veiculo" values( 388 , 'Volvo ', 'Volvo XC40 ');
insert into  public."Veiculo" values( 389 , 'Volskwagen ', 'Voyage ');
insert into  public."Veiculo" values( 390 , ' ', 'Weekend ');
insert into  public."Veiculo" values( 391 , 'Honda ', 'WR-V ');
insert into  public."Veiculo" values( 392 , 'Jeep ', 'Wrangler ');
insert into  public."Veiculo" values( 393 , 'BMW ', 'X1 ');
insert into  public."Veiculo" values( 394 , 'BMW ', 'X2 ');
insert into  public."Veiculo" values( 395 , 'BMW ', 'X3 ');
insert into  public."Veiculo" values( 396 , 'BMW ', 'X4 ');
insert into  public."Veiculo" values( 397 , 'BMW ', 'X5 ');
insert into  public."Veiculo" values( 398 , 'BMW ', 'X6 ');
insert into  public."Veiculo" values( 399 , ' ', 'X60 ');
insert into  public."Veiculo" values( 400 , 'Volvo ', 'XC60 ');
insert into  public."Veiculo" values( 401 , 'Volvo ', 'XC90 ');
insert into  public."Veiculo" values( 402 , ' ', 'XE ');
insert into  public."Veiculo" values( 403 , ' ', 'XF ');
insert into  public."Veiculo" values( 404 , ' ', 'XJ Supersport ');
insert into  public."Veiculo" values( 405 , ' ', 'XKR ');
insert into  public."Veiculo" values( 406 , ' ', 'Xsara Picasso ');
insert into  public."Veiculo" values( 407 , 'Toyota ', 'Yaris ');
insert into  public."Veiculo" values( 408 , ' ', 'Z4 Roadster ');
insert into  public."Veiculo" values( 409 , 'Chevrolet ', 'Zafira ');
insert into  public."Veiculo" values( 410 , ' ', 'Zoe ');